//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhasedakWinService.NiazPardaz {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessagesBL : GhasedakWinService.NiazPardaz.BaseBL {
        
        private long MsgIDField;
        
        private int UserIDField;
        
        private int LinkIDField;
        
        private int NumberIDField;
        
        private double TariffField;
        
        private byte MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdhField;
        
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        private int FirstLocationField;
        
        private int CurrentLocationField;
        
        private int PartsField;
        
        private bool IsFlashField;
        
        private bool IsReadField;
        
        private bool IsUnicodeField;
        
        private double CreditField;
        
        private int ModuleField;
        
        private int RecCountField;
        
        private int RecFailedField;
        
        private int RecSuccessField;
        
        private bool IsMoneyBackField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MsgID {
            get {
                return this.MsgIDField;
            }
            set {
                if ((this.MsgIDField.Equals(value) != true)) {
                    this.MsgIDField = value;
                    this.RaisePropertyChanged("MsgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LinkID {
            get {
                return this.LinkIDField;
            }
            set {
                if ((this.LinkIDField.Equals(value) != true)) {
                    this.LinkIDField = value;
                    this.RaisePropertyChanged("LinkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumberID {
            get {
                return this.NumberIDField;
            }
            set {
                if ((this.NumberIDField.Equals(value) != true)) {
                    this.NumberIDField = value;
                    this.RaisePropertyChanged("NumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Tariff {
            get {
                return this.TariffField;
            }
            set {
                if ((this.TariffField.Equals(value) != true)) {
                    this.TariffField = value;
                    this.RaisePropertyChanged("Tariff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((this.MsgTypeField.Equals(value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Udh {
            get {
                return this.UdhField;
            }
            set {
                if ((object.ReferenceEquals(this.UdhField, value) != true)) {
                    this.UdhField = value;
                    this.RaisePropertyChanged("Udh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int FirstLocation {
            get {
                return this.FirstLocationField;
            }
            set {
                if ((this.FirstLocationField.Equals(value) != true)) {
                    this.FirstLocationField = value;
                    this.RaisePropertyChanged("FirstLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((this.CurrentLocationField.Equals(value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((this.PartsField.Equals(value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsFlash {
            get {
                return this.IsFlashField;
            }
            set {
                if ((this.IsFlashField.Equals(value) != true)) {
                    this.IsFlashField = value;
                    this.RaisePropertyChanged("IsFlash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int RecCount {
            get {
                return this.RecCountField;
            }
            set {
                if ((this.RecCountField.Equals(value) != true)) {
                    this.RecCountField = value;
                    this.RaisePropertyChanged("RecCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int RecFailed {
            get {
                return this.RecFailedField;
            }
            set {
                if ((this.RecFailedField.Equals(value) != true)) {
                    this.RecFailedField = value;
                    this.RaisePropertyChanged("RecFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int RecSuccess {
            get {
                return this.RecSuccessField;
            }
            set {
                if ((this.RecSuccessField.Equals(value) != true)) {
                    this.RecSuccessField = value;
                    this.RaisePropertyChanged("RecSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool IsMoneyBack {
            get {
                return this.IsMoneyBackField;
            }
            set {
                if ((this.IsMoneyBackField.Equals(value) != true)) {
                    this.IsMoneyBackField = value;
                    this.RaisePropertyChanged("IsMoneyBack");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GhasedakWinService.NiazPardaz.MessagesBL))]
    public partial class BaseBL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NiazPardaz.SendSoap")]
    public interface SendSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.SendSimpleSMSResponse SendSimpleSMS(GhasedakWinService.NiazPardaz.SendSimpleSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.SendSimpleSMS2Response SendSimpleSMS2(GhasedakWinService.NiazPardaz.SendSimpleSMS2Request request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.SendSmsResponse SendSms(GhasedakWinService.NiazPardaz.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.GetCreditResponse GetCredit(GhasedakWinService.NiazPardaz.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        int GetDelivery(long recId);
        
        // CODEGEN: Generating message contract since element name recId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.GetDelivery2Response GetDelivery2(GhasedakWinService.NiazPardaz.GetDelivery2Request request);
        
        // CODEGEN: Generating message contract since element name recId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.GetMultiDeliveryResponse GetMultiDelivery(GhasedakWinService.NiazPardaz.GetMultiDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.GetInboxCountResponse GetInboxCount(GhasedakWinService.NiazPardaz.GetInboxCountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        GhasedakWinService.NiazPardaz.getMessagesResponse getMessages(GhasedakWinService.NiazPardaz.getMessagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSimpleSMSRequestBody Body;
        
        public SendSimpleSMSRequest() {
        }
        
        public SendSimpleSMSRequest(GhasedakWinService.NiazPardaz.SendSimpleSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GhasedakWinService.NiazPardaz.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        public SendSimpleSMSRequestBody() {
        }
        
        public SendSimpleSMSRequestBody(string username, string password, GhasedakWinService.NiazPardaz.ArrayOfString to, string from, string text, bool isflash) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSimpleSMSResponseBody Body;
        
        public SendSimpleSMSResponse() {
        }
        
        public SendSimpleSMSResponse(GhasedakWinService.NiazPardaz.SendSimpleSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GhasedakWinService.NiazPardaz.ArrayOfString SendSimpleSMSResult;
        
        public SendSimpleSMSResponseBody() {
        }
        
        public SendSimpleSMSResponseBody(GhasedakWinService.NiazPardaz.ArrayOfString SendSimpleSMSResult) {
            this.SendSimpleSMSResult = SendSimpleSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMS2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS2", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSimpleSMS2RequestBody Body;
        
        public SendSimpleSMS2Request() {
        }
        
        public SendSimpleSMS2Request(GhasedakWinService.NiazPardaz.SendSimpleSMS2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMS2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        public SendSimpleSMS2RequestBody() {
        }
        
        public SendSimpleSMS2RequestBody(string username, string password, string to, string from, string text, bool isflash) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMS2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS2Response", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSimpleSMS2ResponseBody Body;
        
        public SendSimpleSMS2Response() {
        }
        
        public SendSimpleSMS2Response(GhasedakWinService.NiazPardaz.SendSimpleSMS2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMS2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSimpleSMS2Result;
        
        public SendSimpleSMS2ResponseBody() {
        }
        
        public SendSimpleSMS2ResponseBody(string SendSimpleSMS2Result) {
            this.SendSimpleSMS2Result = SendSimpleSMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(GhasedakWinService.NiazPardaz.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GhasedakWinService.NiazPardaz.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public GhasedakWinService.NiazPardaz.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] status;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string username, string password, GhasedakWinService.NiazPardaz.ArrayOfString to, string from, string text, bool isflash, string udh, GhasedakWinService.NiazPardaz.ArrayOfLong recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(GhasedakWinService.NiazPardaz.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GhasedakWinService.NiazPardaz.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(int SendSmsResult, GhasedakWinService.NiazPardaz.ArrayOfLong recId, byte[] status) {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetCreditRequestBody Body;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(GhasedakWinService.NiazPardaz.GetCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody() {
        }
        
        public GetCreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetCreditResponseBody Body;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(GhasedakWinService.NiazPardaz.GetCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody() {
        }
        
        public GetCreditResponseBody(double GetCreditResult) {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDelivery2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery2", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetDelivery2RequestBody Body;
        
        public GetDelivery2Request() {
        }
        
        public GetDelivery2Request(GhasedakWinService.NiazPardaz.GetDelivery2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDelivery2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recId;
        
        public GetDelivery2RequestBody() {
        }
        
        public GetDelivery2RequestBody(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDelivery2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery2Response", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetDelivery2ResponseBody Body;
        
        public GetDelivery2Response() {
        }
        
        public GetDelivery2Response(GhasedakWinService.NiazPardaz.GetDelivery2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDelivery2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDelivery2Result;
        
        public GetDelivery2ResponseBody() {
        }
        
        public GetDelivery2ResponseBody(int GetDelivery2Result) {
            this.GetDelivery2Result = GetDelivery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDelivery", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetMultiDeliveryRequestBody Body;
        
        public GetMultiDeliveryRequest() {
        }
        
        public GetMultiDeliveryRequest(GhasedakWinService.NiazPardaz.GetMultiDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recId;
        
        public GetMultiDeliveryRequestBody() {
        }
        
        public GetMultiDeliveryRequestBody(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetMultiDeliveryResponseBody Body;
        
        public GetMultiDeliveryResponse() {
        }
        
        public GetMultiDeliveryResponse(GhasedakWinService.NiazPardaz.GetMultiDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMultiDeliveryResult;
        
        public GetMultiDeliveryResponseBody() {
        }
        
        public GetMultiDeliveryResponseBody(byte[] GetMultiDeliveryResult) {
            this.GetMultiDeliveryResult = GetMultiDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetInboxCountRequestBody Body;
        
        public GetInboxCountRequest() {
        }
        
        public GetInboxCountRequest(GhasedakWinService.NiazPardaz.GetInboxCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isRead;
        
        public GetInboxCountRequestBody() {
        }
        
        public GetInboxCountRequestBody(string username, string password, bool isRead) {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.GetInboxCountResponseBody Body;
        
        public GetInboxCountResponse() {
        }
        
        public GetInboxCountResponse(GhasedakWinService.NiazPardaz.GetInboxCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponseBody() {
        }
        
        public GetInboxCountResponseBody(int GetInboxCountResult) {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessages", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.getMessagesRequestBody Body;
        
        public getMessagesRequest() {
        }
        
        public getMessagesRequest(GhasedakWinService.NiazPardaz.getMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public getMessagesRequestBody() {
        }
        
        public getMessagesRequestBody(string username, string password, int location, string from, int index, int count) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.NiazPardaz.getMessagesResponseBody Body;
        
        public getMessagesResponse() {
        }
        
        public getMessagesResponse(GhasedakWinService.NiazPardaz.getMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GhasedakWinService.NiazPardaz.MessagesBL[] getMessagesResult;
        
        public getMessagesResponseBody() {
        }
        
        public getMessagesResponseBody(GhasedakWinService.NiazPardaz.MessagesBL[] getMessagesResult) {
            this.getMessagesResult = getMessagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SendSoapChannel : GhasedakWinService.NiazPardaz.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<GhasedakWinService.NiazPardaz.SendSoap>, GhasedakWinService.NiazPardaz.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.SendSimpleSMSResponse GhasedakWinService.NiazPardaz.SendSoap.SendSimpleSMS(GhasedakWinService.NiazPardaz.SendSimpleSMSRequest request) {
            return base.Channel.SendSimpleSMS(request);
        }
        
        public GhasedakWinService.NiazPardaz.ArrayOfString SendSimpleSMS(string username, string password, GhasedakWinService.NiazPardaz.ArrayOfString to, string from, string text, bool isflash) {
            GhasedakWinService.NiazPardaz.SendSimpleSMSRequest inValue = new GhasedakWinService.NiazPardaz.SendSimpleSMSRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.SendSimpleSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            GhasedakWinService.NiazPardaz.SendSimpleSMSResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).SendSimpleSMS(inValue);
            return retVal.Body.SendSimpleSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.SendSimpleSMS2Response GhasedakWinService.NiazPardaz.SendSoap.SendSimpleSMS2(GhasedakWinService.NiazPardaz.SendSimpleSMS2Request request) {
            return base.Channel.SendSimpleSMS2(request);
        }
        
        public string SendSimpleSMS2(string username, string password, string to, string from, string text, bool isflash) {
            GhasedakWinService.NiazPardaz.SendSimpleSMS2Request inValue = new GhasedakWinService.NiazPardaz.SendSimpleSMS2Request();
            inValue.Body = new GhasedakWinService.NiazPardaz.SendSimpleSMS2RequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            GhasedakWinService.NiazPardaz.SendSimpleSMS2Response retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).SendSimpleSMS2(inValue);
            return retVal.Body.SendSimpleSMS2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.SendSmsResponse GhasedakWinService.NiazPardaz.SendSoap.SendSms(GhasedakWinService.NiazPardaz.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, GhasedakWinService.NiazPardaz.ArrayOfString to, string from, string text, bool isflash, string udh, ref GhasedakWinService.NiazPardaz.ArrayOfLong recId, ref byte[] status) {
            GhasedakWinService.NiazPardaz.SendSmsRequest inValue = new GhasedakWinService.NiazPardaz.SendSmsRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            GhasedakWinService.NiazPardaz.SendSmsResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).SendSms(inValue);
            recId = retVal.Body.recId;
            status = retVal.Body.status;
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.GetCreditResponse GhasedakWinService.NiazPardaz.SendSoap.GetCredit(GhasedakWinService.NiazPardaz.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public double GetCredit(string username, string password) {
            GhasedakWinService.NiazPardaz.GetCreditRequest inValue = new GhasedakWinService.NiazPardaz.GetCreditRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            GhasedakWinService.NiazPardaz.GetCreditResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).GetCredit(inValue);
            return retVal.Body.GetCreditResult;
        }
        
        public int GetDelivery(long recId) {
            return base.Channel.GetDelivery(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.GetDelivery2Response GhasedakWinService.NiazPardaz.SendSoap.GetDelivery2(GhasedakWinService.NiazPardaz.GetDelivery2Request request) {
            return base.Channel.GetDelivery2(request);
        }
        
        public int GetDelivery2(string recId) {
            GhasedakWinService.NiazPardaz.GetDelivery2Request inValue = new GhasedakWinService.NiazPardaz.GetDelivery2Request();
            inValue.Body = new GhasedakWinService.NiazPardaz.GetDelivery2RequestBody();
            inValue.Body.recId = recId;
            GhasedakWinService.NiazPardaz.GetDelivery2Response retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).GetDelivery2(inValue);
            return retVal.Body.GetDelivery2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.GetMultiDeliveryResponse GhasedakWinService.NiazPardaz.SendSoap.GetMultiDelivery(GhasedakWinService.NiazPardaz.GetMultiDeliveryRequest request) {
            return base.Channel.GetMultiDelivery(request);
        }
        
        public byte[] GetMultiDelivery(string recId) {
            GhasedakWinService.NiazPardaz.GetMultiDeliveryRequest inValue = new GhasedakWinService.NiazPardaz.GetMultiDeliveryRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.GetMultiDeliveryRequestBody();
            inValue.Body.recId = recId;
            GhasedakWinService.NiazPardaz.GetMultiDeliveryResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).GetMultiDelivery(inValue);
            return retVal.Body.GetMultiDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.GetInboxCountResponse GhasedakWinService.NiazPardaz.SendSoap.GetInboxCount(GhasedakWinService.NiazPardaz.GetInboxCountRequest request) {
            return base.Channel.GetInboxCount(request);
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            GhasedakWinService.NiazPardaz.GetInboxCountRequest inValue = new GhasedakWinService.NiazPardaz.GetInboxCountRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            GhasedakWinService.NiazPardaz.GetInboxCountResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).GetInboxCount(inValue);
            return retVal.Body.GetInboxCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.NiazPardaz.getMessagesResponse GhasedakWinService.NiazPardaz.SendSoap.getMessages(GhasedakWinService.NiazPardaz.getMessagesRequest request) {
            return base.Channel.getMessages(request);
        }
        
        public GhasedakWinService.NiazPardaz.MessagesBL[] getMessages(string username, string password, int location, string from, int index, int count) {
            GhasedakWinService.NiazPardaz.getMessagesRequest inValue = new GhasedakWinService.NiazPardaz.getMessagesRequest();
            inValue.Body = new GhasedakWinService.NiazPardaz.getMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            GhasedakWinService.NiazPardaz.getMessagesResponse retVal = ((GhasedakWinService.NiazPardaz.SendSoap)(this)).getMessages(inValue);
            return retVal.Body.getMessagesResult;
        }
    }
}
