//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhasedakWinService.SMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.smsSoap")]
    public interface smsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        GhasedakWinService.SMSService.HelloWorldResponse HelloWorld(GhasedakWinService.SMSService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendSMS", ReplyAction="*")]
        GhasedakWinService.SMSService.doSendSMSResponse doSendSMS(GhasedakWinService.SMSService.doSendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMS", ReplyAction="*")]
        GhasedakWinService.SMSService.doReceiveSMSResponse doReceiveSMS(GhasedakWinService.SMSService.doReceiveSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDelivery", ReplyAction="*")]
        GhasedakWinService.SMSService.getDeliveryResponse getDelivery(GhasedakWinService.SMSService.getDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfo", ReplyAction="*")]
        GhasedakWinService.SMSService.getInfoResponse getInfo(GhasedakWinService.SMSService.getInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(GhasedakWinService.SMSService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(GhasedakWinService.SMSService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMS", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.doSendSMSRequestBody Body;
        
        public doSendSMSRequest() {
        }
        
        public doSendSMSRequest(GhasedakWinService.SMSService.doSendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uCellphones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool uFarsi;
        
        public doSendSMSRequestBody() {
        }
        
        public doSendSMSRequestBody(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphones = uCellphones;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.doSendSMSResponseBody Body;
        
        public doSendSMSResponse() {
        }
        
        public doSendSMSResponse(GhasedakWinService.SMSService.doSendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doSendSMSResult;
        
        public doSendSMSResponseBody() {
        }
        
        public doSendSMSResponseBody(string doSendSMSResult) {
            this.doSendSMSResult = doSendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMS", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.doReceiveSMSRequestBody Body;
        
        public doReceiveSMSRequest() {
        }
        
        public doReceiveSMSRequest(GhasedakWinService.SMSService.doReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSRequestBody() {
        }
        
        public doReceiveSMSRequestBody(string uUsername, string uPassword, long uLastRowID) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.doReceiveSMSResponseBody Body;
        
        public doReceiveSMSResponse() {
        }
        
        public doReceiveSMSResponse(GhasedakWinService.SMSService.doReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doReceiveSMSResult;
        
        public doReceiveSMSResponseBody() {
        }
        
        public doReceiveSMSResponseBody(string doReceiveSMSResult) {
            this.doReceiveSMSResult = doReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDelivery", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.getDeliveryRequestBody Body;
        
        public getDeliveryRequest() {
        }
        
        public getDeliveryRequest(GhasedakWinService.SMSService.getDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public getDeliveryRequestBody() {
        }
        
        public getDeliveryRequestBody(string uUsername, string uReturnIDs) {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.getDeliveryResponseBody Body;
        
        public getDeliveryResponse() {
        }
        
        public getDeliveryResponse(GhasedakWinService.SMSService.getDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeliveryResult;
        
        public getDeliveryResponseBody() {
        }
        
        public getDeliveryResponseBody(string getDeliveryResult) {
            this.getDeliveryResult = getDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfo", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.getInfoRequestBody Body;
        
        public getInfoRequest() {
        }
        
        public getInfoRequest(GhasedakWinService.SMSService.getInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public getInfoRequestBody() {
        }
        
        public getInfoRequestBody(string uUsername, string uPassword) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public GhasedakWinService.SMSService.getInfoResponseBody Body;
        
        public getInfoResponse() {
        }
        
        public getInfoResponse(GhasedakWinService.SMSService.getInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInfoResult;
        
        public getInfoResponseBody() {
        }
        
        public getInfoResponseBody(string getInfoResult) {
            this.getInfoResult = getInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface smsSoapChannel : GhasedakWinService.SMSService.smsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class smsSoapClient : System.ServiceModel.ClientBase<GhasedakWinService.SMSService.smsSoap>, GhasedakWinService.SMSService.smsSoap {
        
        public smsSoapClient() {
        }
        
        public smsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.SMSService.HelloWorldResponse GhasedakWinService.SMSService.smsSoap.HelloWorld(GhasedakWinService.SMSService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            GhasedakWinService.SMSService.HelloWorldRequest inValue = new GhasedakWinService.SMSService.HelloWorldRequest();
            inValue.Body = new GhasedakWinService.SMSService.HelloWorldRequestBody();
            GhasedakWinService.SMSService.HelloWorldResponse retVal = ((GhasedakWinService.SMSService.smsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.SMSService.doSendSMSResponse GhasedakWinService.SMSService.smsSoap.doSendSMS(GhasedakWinService.SMSService.doSendSMSRequest request) {
            return base.Channel.doSendSMS(request);
        }
        
        public string doSendSMS(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi) {
            GhasedakWinService.SMSService.doSendSMSRequest inValue = new GhasedakWinService.SMSService.doSendSMSRequest();
            inValue.Body = new GhasedakWinService.SMSService.doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            GhasedakWinService.SMSService.doSendSMSResponse retVal = ((GhasedakWinService.SMSService.smsSoap)(this)).doSendSMS(inValue);
            return retVal.Body.doSendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.SMSService.doReceiveSMSResponse GhasedakWinService.SMSService.smsSoap.doReceiveSMS(GhasedakWinService.SMSService.doReceiveSMSRequest request) {
            return base.Channel.doReceiveSMS(request);
        }
        
        public string doReceiveSMS(string uUsername, string uPassword, long uLastRowID) {
            GhasedakWinService.SMSService.doReceiveSMSRequest inValue = new GhasedakWinService.SMSService.doReceiveSMSRequest();
            inValue.Body = new GhasedakWinService.SMSService.doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            GhasedakWinService.SMSService.doReceiveSMSResponse retVal = ((GhasedakWinService.SMSService.smsSoap)(this)).doReceiveSMS(inValue);
            return retVal.Body.doReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.SMSService.getDeliveryResponse GhasedakWinService.SMSService.smsSoap.getDelivery(GhasedakWinService.SMSService.getDeliveryRequest request) {
            return base.Channel.getDelivery(request);
        }
        
        public string getDelivery(string uUsername, string uReturnIDs) {
            GhasedakWinService.SMSService.getDeliveryRequest inValue = new GhasedakWinService.SMSService.getDeliveryRequest();
            inValue.Body = new GhasedakWinService.SMSService.getDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            GhasedakWinService.SMSService.getDeliveryResponse retVal = ((GhasedakWinService.SMSService.smsSoap)(this)).getDelivery(inValue);
            return retVal.Body.getDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhasedakWinService.SMSService.getInfoResponse GhasedakWinService.SMSService.smsSoap.getInfo(GhasedakWinService.SMSService.getInfoRequest request) {
            return base.Channel.getInfo(request);
        }
        
        public string getInfo(string uUsername, string uPassword) {
            GhasedakWinService.SMSService.getInfoRequest inValue = new GhasedakWinService.SMSService.getInfoRequest();
            inValue.Body = new GhasedakWinService.SMSService.getInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            GhasedakWinService.SMSService.getInfoResponse retVal = ((GhasedakWinService.SMSService.smsSoap)(this)).getInfo(inValue);
            return retVal.Body.getInfoResult;
        }
    }
}
